# Generated by Django 3.2 on 2023-04-24 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lote',
            old_name='latitude',
            new_name='identificacao',
        ),
        migrations.RemoveField(
            model_name='lote',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='lote',
            name='numero',
        ),
        migrations.CreateModel(
            name='Quadra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacao', models.CharField(blank=True, max_length=50, null=True)),
                ('loteamento', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cadastros.loteamento')),
            ],
        ),
        migrations.AddField(
            model_name='lote',
            name='quadra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cadastros.quadra'),
        ),
    ]
