# Generated by Django 3.2 on 2023-04-25 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0004_rename_rg_contatocliente_contato'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='status',
            field=models.CharField(choices=[('REALIZADA', 'REALIZADA'), ('ENTRADA PAGA', 'ENTRADA PAGA'), ('CANCELADA', 'CANCELADA')], default='REALIZADA', max_length=20),
        ),
    ]
